### ISSUE TITLE
Investigate and Implement GitGraph

### ISSUE THREAD

**Issue by lokai-sh** [rostgoat/photogallery#28]
Part of the assignment is to demonstrate GitGraph.

We will need to research the tool and get it working so we can demonstrate it

**Comment by nitingupta776** [comment]
Can use this git command in the machine terminal/ command prompt where the local git repository has been set up
 for this PhotoGallery App project: git log --all --decorate --oneline --graph 

<img width="1440" alt="Screen Shot 2020-10-04 at 5 06 27 PM" src="https://user-images.githubusercontent.com/17343206/95030335-f2cd4580-0663-11eb-9d82-21350af5d005.png">
