### ISSUE TITLE
Create automated test for Key Word Search

### ISSUE THREAD

**Issue by lokai-sh** [rostgoat/photogallery#29]
The test shall automatically invoke Gallery Activity, press the search  button of this Activity to bring Search Activity to the foreground, enter startdate, enddate and/or keywords that should result in finding only one photo, press OK button to bring back the Gallery Activity, check the timestamp and caption to verify that the right picture was found.

**Comment by nitingupta776** [comment]
Wrote the  automated UI test cases using Espresso, also did manual testing to test the basic functionality for all the buttons that were implemented for Sprint 1
