### ISSUE TITLE
Setup Continuous Integration and Testing

### ISSUE THREAD

**Issue by lokai-sh** [rostgoat/photogallery#31]
Setup the automated build and testing functionality using Git/Jenkins or some other alternative CIT solution showing that build was successful and automated tests ran

**Comment by nitingupta776** [comment]
Configure Jenkins to do the following:
-Successfully building the project that is connected with the project's Github repository master branch
- Running an android emulator on local machine using gradle wrapper and performing the automated UI tests
- Console output of the complete build from Jenkins
<img width="1440" alt="Screen Shot 2020-10-04 at 5 13 56 PM" src="https://user-images.githubusercontent.com/17343206/95030490-ff05d280-0664-11eb-848c-67b17c710e67.png">
<img width="1440" alt="Screen Shot 2020-10-04 at 5 14 17 PM" src="https://user-images.githubusercontent.com/17343206/95030494-0b8a2b00-0665-11eb-8009-39d5c6c2dcff.png">
<img width="1440" alt="Screen Shot 2020-10-04 at 5 14 36 PM" src="https://user-images.githubusercontent.com/17343206/95030501-1775ed00-0665-11eb-9e91-798a6c264610.png">
<img width="1440" alt="Screen Shot 2020-10-04 at 5 14 51 PM" src="https://user-images.githubusercontent.com/17343206/95030505-1fce2800-0665-11eb-92a8-1d518c05ee21.png">
