### ISSUE TITLE
Implement AOP

### ISSUE THREAD

**Issue by rostgoat** [rostgoat/photogallery#38]
Aspect Oriented Programming feature [preferably using AspectJ]

**Comment by lokai-sh** [comment]
AspectJ has been implemented using custom annotations and the creation of an aspect called LogAspect

- Create a custom annotation called 'LogAnnotation'
- Created a LogAspect that looks for this annotation in the code
- When it finds the annotation it logs the name of the method that was annotated.

This is a simple example of AspectJ. The idea then is that the aspectJ injects in the logging code wherever the annotation is. When you grab the code after I commit it you will see the logging in the Logcat tab at the bottom of Android Studio. I added a filter into the LogCat screen for 'LogAspect' so I only see those messages
